### ISSUE TITLE
Why GPL3 ? (Edit: Switch to Apache 2.0)

### ISSUE THREAD

**Issue by TheBricktop** [voxell-tech/UnitySpeechEngine#1]
It is common conception that gpl3 is pretty restrictive when it comes to linking the gpled libraries with other software, so for example if one would link this repo to their game it could mean that this game will be gpled too. Not everybody wants to give out all their work considering the virality of said gpl license.
Wouldnt it be wiser to use LGPL3 that allows using libraries linked to the closed source without infecting it with license?

**Comment by nixonyh** [comment]
hi hi, so sorry I haven't have time to change this repo's license! It is supposed to be Apache 2.0 XD, please feel free to use it on any projects!

**Comment by TheBricktop** [comment]
Dont need to be sorry, just was curious if its deliberate or not.
Apache 2 is the warm fuzzy license everybody loves .

**Comment by nixonyh** [comment]
hi, I have switched this repo to Apache 2.0 alongside with a alpha release of v0.0.1 :)

**Comment by TheBricktop** [comment]
Awesome thank You.
